name: Docker

on: [push, pull_request]

permissions:
  packages: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "corretto"

            - name: Build Docker image
              run: |
                  docker build -t building-signal-simulator .

            - name: Log in to GitHub Container Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Tag and push Docker image
              if: github.event_name != 'pull_request'
              run: |
                  IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/building-signal-simulator:latest
                  docker tag building-signal-simulator $IMAGE_NAME
                  docker push $IMAGE_NAME
